import "../styles/globals.css";
import "@radix-ui/themes/styles.css";

import React from "react";
import { Theme } from "@radix-ui/themes";
import LogoutButton from "./_components/LogoutButton";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Theme appearance="dark">
          <div className="bg-blue-500 text-white p-4">
              <LogoutButton />
          </div>
          {children}
        </Theme>
      </body>
    </html>
  );
}
